<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-20 at 17:21:59.
 */
class Model_RapportvisiteTest extends PHPUnit_Framework_TestCase {

    public function dataCheckDate() {
        return array(
            array(array(# test 0 lettres
                    'string' => 'wfb',
                    'result' => false
                )),
            array(array(# test 1 pas de tirets
                    'string' => '121415',
                    'result' => false
                )),
            array(array(#test 2 juste
                    'string' => '12-01-2014',
                    'result' => true
                )),
            array(array(#test 3 mois incorrect
                    'string' => '12-23-2014',
                    'result' => false
                )),
            array(array(#test 4 espace, juste
                    'string' => '12-01-2014 ',
                    'result' => true
                ))
        );
    }

    /**
     * @dataProvider dataCheckDate
     */
    public function testCheckDate($data) {
        $rapport = New Model_Rapportvisite();
        $date = $data['string'];
        $return = $rapport->checkDate($date);
        $this->assertEquals($data['result'], $return);
        $this->assertSame($data['result'], $return);
    }

    public function dataCheckCoef() {
        return array(
            array(array(#test 5 
                    'string' => '0,9',
                    'result' => false
                )),
            array(array(#test 6 
                    'string' => '0.9',
                    'result' => true
                )),
            array(array(#test 7
                    'string' => null,
                    'result' => true
                )),
            array(array(#test 8
                    'string' => 'evdf',
                    'result' => false
                ))
        );
    }

    /**
     * 
     * @dataProvider dataCheckCoef
     */
    public function testCheckCoef($data) {
        $rapport = New Model_Rapportvisite();
        $coef = $data['string'];
        $return = $rapport->checkCoef($coef);
        $this->assertEquals($data['result'], $return);
        $this->assertSame($data['result'], $return);
    }

    public function dataCheckDuree() {
        return array(
            array(array(#test 9 
                    'string' => '0,9',
                    'result' => false,
                    'db' => null
                )),
            array(array(#test 10
                    'string' => '09',
                    'result' => true,
                    'db' => '00:09:00'
                )),
            array(array(#test 11
                    'string' => '9',
                    'result' => true,
                    'db' => '00:09:00'
                )),
            array(array(#test 12
                    'string' => 'evdf',
                    'result' => false,
                    'db' => null
                ))
        );
    }

    /**
     * 
     * @dataProvider dataCheckDuree
     */
    public function testCheckDuree($data) {
        $rapport = New Model_Rapportvisite();
        $duree = $data['string'];
        $return = $rapport->checkDuree($duree);
        $this->assertEquals($data['result'], $return);
        $this->assertSame($data['result'], $return);
        $db = $rapport->dureeSaisie;
        $this->assertEquals($data['db'], $db);
        $this->assertSame($data['db'], $db);
    }

    public function dataCheckDonnees() {
        return array(
            array(array(#test 13 
                    'date' => true,
                    'coef' => false,
                    'duree' => true,
                    'result' => false
                )),
            array(array(#test 14
                    'date' => false,
                    'coef' => false,
                    'duree' => false,
                    'result' => false
                )),
            array(array(#test 15
                    'date' => true,
                    'coef' => true,
                    'duree' => true,
                    'result' => true
                ))
        );
    }

    /**
     * 
     * @dataProvider dataCheckDonnees
     */
    public function testCheckDonnees($data) {
        $rapport = New Model_Rapportvisite();
        $duree = $data['duree'];
        $date = $data['date'];
        $coef = $data['coef'];
        $return = $rapport->checkDonnees($date,$coef,$duree);
        $this->assertEquals($data['result'], $return);
        $this->assertSame($data['result'], $return);
    }

}
